version: '3'

services:
  news-extractor:
    build: ./extract
    ports:
      - 8001:8000
    networks:
      etl:
        ipv4_address: 10.23.4.2
    depends_on:
      - news-store-mongo
  
  news-store-mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      etl:
        ipv4_address: 10.23.4.3
  
  sentiment-contaienr:
    build: ./sentiment-analysis
    ports:
      - 8002:8000
    networks:
      etl:
        ipv4_address: 10.23.4.4
networks:
  etl:
    ipam:
      config:
        - subnet: "10.23.4.0/24"
    
    